import Database from 'better-sqlite3'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import * as schema from './schema'
import { destinations, flights } from './schema'

const sqlite = new Database('travel.db')
export const db = drizzle(sqlite, { schema })

// Run migrations (create tables if not exist)
sqlite.exec(`
  CREATE TABLE IF NOT EXISTS destinations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    description TEXT NOT NULL,
    long_description TEXT NOT NULL,
    price REAL NOT NULL,
    image TEXT NOT NULL,
    rating REAL NOT NULL,
    category TEXT NOT NULL,
    temperature TEXT NOT NULL,
    flight_hours REAL NOT NULL,
    best_season TEXT NOT NULL,
    highlights TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    destination_id INTEGER NOT NULL REFERENCES destinations(id),
    travel_date TEXT NOT NULL,
    return_date TEXT NOT NULL,
    travelers INTEGER NOT NULL DEFAULT 1,
    total_price REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'confirmed',
    created_at INTEGER
  );

  CREATE TABLE IF NOT EXISTS wishlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    destination_id INTEGER NOT NULL REFERENCES destinations(id),
    created_at INTEGER,
    UNIQUE(user_id, destination_id)
  );

  CREATE TABLE IF NOT EXISTS flights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    airline TEXT NOT NULL,
    from_code TEXT NOT NULL,
    to_code TEXT NOT NULL,
    from_city TEXT NOT NULL,
    to_city TEXT NOT NULL,
    departure TEXT NOT NULL,
    arrival TEXT NOT NULL,
    duration TEXT NOT NULL,
    price REAL NOT NULL,
    stops INTEGER NOT NULL DEFAULT 0,
    stops_label TEXT NOT NULL,
    rating REAL NOT NULL,
    features TEXT NOT NULL,
    badge TEXT
  );
`)

// Seed destinations if empty
const existing = db.select().from(destinations).limit(1).all()
if (existing.length === 0) {
  db.insert(destinations).values([
    {
      name: 'Kyoto',
      country: 'Japan',
      description: 'Ancient temples and cherry blossom perfection',
      longDescription: 'Step into a world where centuries-old temples stand beside bamboo groves and geisha districts. Kyoto, the cultural heart of Japan, offers a journey through time with over 1,600 Buddhist temples, 400 Shinto shrines, and perfectly preserved wooden machiya townhouses. Spring transforms the city into a sea of pink cherry blossoms, while autumn paints it in fiery reds and golds.',
      price: 1800,
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
      rating: 4.9,
      category: 'City',
      temperature: '15°C',
      flightHours: 14,
      bestSeason: 'Spring',
      highlights: JSON.stringify(['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji Temple', 'Gion District']),
    },
    {
      name: 'Santorini',
      country: 'Greece',
      description: 'Whitewashed cliffs and legendary sunsets',
      longDescription: 'Perched on the rim of a volcanic caldera, Santorini is one of the world\'s most iconic destinations. The island\'s distinctive blue-domed churches, whitewashed buildings, and breathtaking caldera views have made it a bucket-list favorite. Watch the famous sunset from Oia, explore ancient ruins at Akrotiri, and relax on volcanic black-sand beaches.',
      price: 2200,
      image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
      rating: 4.8,
      category: 'Beach',
      temperature: '25°C',
      flightHours: 11,
      bestSeason: 'Summer',
      highlights: JSON.stringify(['Oia Sunset', 'Caldera Views', 'Red Beach', 'Akrotiri Ruins']),
    },
    {
      name: 'Banff',
      country: 'Canada',
      description: 'Turquoise lakes and soaring Rocky Mountain peaks',
      longDescription: 'Nestled in the heart of the Canadian Rockies, Banff National Park is a wonderland of glaciers, turquoise glacial lakes, and wildlife. Lake Louise and Moraine Lake are among the most photographed places on Earth, their impossible blue-green waters reflecting the surrounding mountains. Whether skiing in winter or hiking in summer, Banff delivers unforgettable wilderness experiences.',
      price: 1500,
      image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
      rating: 5.0,
      category: 'Mountain',
      temperature: '8°C',
      flightHours: 10,
      bestSeason: 'Summer',
      highlights: JSON.stringify(['Lake Louise', 'Moraine Lake', 'Banff Gondola', 'Johnston Canyon']),
    },
    {
      name: 'Maui',
      country: 'USA',
      description: 'Volcanic landscapes meet tropical paradise',
      longDescription: 'The Valley Isle of Maui blends dramatic volcanic landscapes with lush rainforests and pristine beaches. Drive the legendary Road to Hana through 64 miles of waterfalls, tropical flora, and black-sand beaches. Watch the sunrise from Haleakalā volcano\'s summit at 10,000 feet, then snorkel with sea turtles in crystal-clear waters at Molokini Crater.',
      price: 2800,
      image: 'https://images.unsplash.com/photo-1505852673533-91b5a5d05494?w=800&q=80',
      rating: 4.7,
      category: 'Tropical',
      temperature: '28°C',
      flightHours: 9,
      bestSeason: 'Winter',
      highlights: JSON.stringify(['Road to Hana', 'Haleakalā Sunrise', 'Molokini Snorkeling', 'Ka\'anapali Beach']),
    },
    {
      name: 'Amalfi Coast',
      country: 'Italy',
      description: 'Dramatic cliffs, colorful villages and azure waters',
      longDescription: 'The Amalfi Coast stretches for 50 kilometers along the southern edge of the Sorrentine Peninsula, a UNESCO World Heritage Site of breathtaking beauty. Colorful fishing villages cling to steep cliffs above the azure Tyrrhenian Sea, while winding coastal roads offer heart-stopping views at every turn. Indulge in fresh seafood, limoncello, and la dolce vita.',
      price: 2500,
      image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80',
      rating: 4.9,
      category: 'Beach',
      temperature: '24°C',
      flightHours: 12,
      bestSeason: 'Summer',
      highlights: JSON.stringify(['Positano Village', 'Path of the Gods Hike', 'Ravello Gardens', 'Boat Tour']),
    },
    {
      name: 'Zion National Park',
      country: 'USA',
      description: 'Towering sandstone canyons and slot canyon hikes',
      longDescription: 'Zion National Park is Utah\'s most visited national park, drawing millions with its towering sandstone cliffs, emerald pools, and the legendary Narrows slot canyon hike. Angels Landing\'s chain-assisted climb rewards hikers with panoramic views of Zion Canyon. The park\'s unique geography creates a series of diverse ecosystems, from desert to riparian to conifer forest.',
      price: 1200,
      image: 'https://images.unsplash.com/photo-1504893524553-f8591ce2d0dd?w=800&q=80',
      rating: 4.8,
      category: 'Mountain',
      temperature: '18°C',
      flightHours: 6,
      bestSeason: 'Spring',
      highlights: JSON.stringify(['The Narrows', 'Angels Landing', 'Emerald Pools', 'Canyon Overlook Trail']),
    },
    {
      name: 'Swiss Alps',
      country: 'Switzerland',
      description: 'Pristine peaks, alpine villages and world-class skiing',
      longDescription: 'The Swiss Alps represent the pinnacle of mountain travel, with some of Europe\'s highest peaks, most charming villages, and best ski resorts. Zermatt sits car-free beneath the iconic Matterhorn, while Grindelwald offers front-row views of the Eiger North Face. In summer, the meadows bloom with wildflowers and hiking trails wind through breathtaking high-altitude scenery.',
      price: 3200,
      image: 'https://images.unsplash.com/photo-1531310197839-ccf54637d097?w=800&q=80',
      rating: 5.0,
      category: 'Mountain',
      temperature: '5°C',
      flightHours: 13,
      bestSeason: 'Winter',
      highlights: JSON.stringify(['Matterhorn', 'Jungfraujoch', 'Zermatt Village', 'Glacier Express']),
    },
    {
      name: 'Tulum',
      country: 'Mexico',
      description: 'Mayan ruins overlooking Caribbean turquoise waters',
      longDescription: 'Tulum uniquely combines archaeological wonder with natural beauty — ancient Mayan ruins perch dramatically atop limestone cliffs above brilliant turquoise Caribbean waters. Below, pristine beaches invite relaxation, while the surrounding jungle hides cenotes (sacred sinkholes) perfect for swimming. The town has emerged as a hub for eco-luxury travel, yoga retreats, and farm-to-table dining.',
      price: 1600,
      image: 'https://images.unsplash.com/photo-1504730655501-24c39ac53f0e?w=800&q=80',
      rating: 4.6,
      category: 'Beach',
      temperature: '29°C',
      flightHours: 4,
      bestSeason: 'Winter',
      highlights: JSON.stringify(['Tulum Ruins', 'Cenote Dos Ojos', 'Gran Cenote', 'Sian Ka\'an Biosphere']),
    },
  ]).run()
}

// Seed flights if empty
const existingFlights = db.select().from(flights).limit(1).all()
if (existingFlights.length === 0) {
  db.insert(flights).values([
    {
      airline: 'Emirates',
      fromCode: 'JFK',
      toCode: 'DXB',
      fromCity: 'New York',
      toCity: 'Dubai',
      departure: '08:30 AM',
      arrival: '06:45 PM',
      duration: '14h 15m',
      price: 1240,
      stops: 0,
      stopsLabel: 'Non-stop',
      rating: 4.9,
      features: JSON.stringify(['WiFi','Meals','Entertainment']),
      badge: 'Best Value',
    },
    {
      airline: 'Singapore Airlines',
      fromCode: 'LHR',
      toCode: 'SIN',
      fromCity: 'London',
      toCity: 'Singapore',
      departure: '11:15 AM',
      arrival: '07:30 AM+1',
      duration: '13h 15m',
      price: 1380,
      stops: 0,
      stopsLabel: 'Non-stop',
      rating: 4.8,
      features: JSON.stringify(['WiFi','Meals','Entertainment','Lie-flat']),
      badge: 'Top Rated',
    },
    {
      airline: 'Qatar Airways',
      fromCode: 'CDG',
      toCode: 'BKK',
      fromCity: 'Paris',
      toCity: 'Bangkok',
      departure: '02:45 PM',
      arrival: '10:20 AM+1',
      duration: '11h 35m',
      price: 980,
      stops: 1,
      stopsLabel: '1 Stop DOH',
      rating: 4.7,
      features: JSON.stringify(['Meals','Entertainment']),
    },
    {
      airline: 'Turkish Airlines',
      fromCode: 'FRA',
      toCode: 'NRT',
      fromCity: 'Frankfurt',
      toCity: 'Tokyo',
      departure: '10:00 AM',
      arrival: '06:30 AM+1',
      duration: '15h 30m',
      price: 860,
      stops: 1,
      stopsLabel: '1 Stop IST',
      rating: 4.5,
      features: JSON.stringify(['WiFi','Meals']),
    },
    {
      airline: 'Etihad',
      fromCode: 'SYD',
      toCode: 'LHR',
      fromCity: 'Sydney',
      toCity: 'London',
      departure: '09:50 PM',
      arrival: '05:15 PM',
      duration: '24h 25m',
      price: 1560,
      stops: 1,
      stopsLabel: '1 Stop AUH',
      rating: 4.6,
      features: JSON.stringify(['WiFi','Meals','Entertainment','Lie-flat']),
    },
    {
      airline: 'Japan Airlines',
      fromCode: 'LAX',
      toCode: 'HND',
      fromCity: 'Los Angeles',
      toCity: 'Tokyo',
      departure: '12:30 PM',
      arrival: '04:30 PM+1',
      duration: '12h 00m',
      price: 1120,
      stops: 0,
      stopsLabel: 'Non-stop',
      rating: 4.8,
      features: JSON.stringify(['WiFi','Meals','Entertainment']),
      badge: 'Trending',
    },
  ]).run()
}
