/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as NavRouteImport } from './routes/nav'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as NavIndexRouteImport } from './routes/nav.index'
import { Route as ShopProductsRouteImport } from './routes/shop.products'
import { Route as ProductsChar123CategoryChar125RouteImport } from './routes/products.{-$category}'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PostsSplatRouteImport } from './routes/posts.$'
import { Route as NavSearchRouteImport } from './routes/nav.search'
import { Route as NavRedirectRouteImport } from './routes/nav.redirect'
import { Route as PathlessLayoutDashboardRouteImport } from './routes/_pathlessLayout.dashboard'
import { Route as ShopProductsProductIdRouteImport } from './routes/shop.products.$productId'
import { Route as PostsPostIdEditRouteImport } from './routes/posts_.$postId.edit'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const NavRoute = NavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const NavIndexRoute = NavIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavRoute,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChar123CategoryChar125Route =
  ProductsChar123CategoryChar125RouteImport.update({
    id: '/products/{-$category}',
    path: '/products/{-$category}',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const PostsSplatRoute = PostsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PostsRoute,
} as any)
const NavSearchRoute = NavSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => NavRoute,
} as any)
const NavRedirectRoute = NavRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => NavRoute,
} as any)
const PathlessLayoutDashboardRoute = PathlessLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const ShopProductsProductIdRoute = ShopProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopProductsRoute,
} as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/posts_/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/nav': typeof NavRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/nav/redirect': typeof NavRedirectRoute
  '/nav/search': typeof NavSearchRoute
  '/posts/$': typeof PostsSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/{-$category}': typeof ProductsChar123CategoryChar125Route
  '/shop/products': typeof ShopProductsRouteWithChildren
  '/nav/': typeof NavIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/shop/products/$productId': typeof ShopProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/nav/redirect': typeof NavRedirectRoute
  '/nav/search': typeof NavSearchRoute
  '/posts/$': typeof PostsSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/{-$category}': typeof ProductsChar123CategoryChar125Route
  '/shop/products': typeof ShopProductsRouteWithChildren
  '/nav': typeof NavIndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/shop/products/$productId': typeof ShopProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/nav': typeof NavRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/_pathlessLayout/dashboard': typeof PathlessLayoutDashboardRoute
  '/nav/redirect': typeof NavRedirectRoute
  '/nav/search': typeof NavSearchRoute
  '/posts/$': typeof PostsSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/{-$category}': typeof ProductsChar123CategoryChar125Route
  '/shop/products': typeof ShopProductsRouteWithChildren
  '/nav/': typeof NavIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts_/$postId/edit': typeof PostsPostIdEditRoute
  '/shop/products/$productId': typeof ShopProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/nav'
    | '/posts'
    | '/dashboard'
    | '/nav/redirect'
    | '/nav/search'
    | '/posts/$'
    | '/posts/$postId'
    | '/products/{-$category}'
    | '/shop/products'
    | '/nav/'
    | '/posts/'
    | '/posts/$postId/edit'
    | '/shop/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/nav/redirect'
    | '/nav/search'
    | '/posts/$'
    | '/posts/$postId'
    | '/products/{-$category}'
    | '/shop/products'
    | '/nav'
    | '/posts'
    | '/posts/$postId/edit'
    | '/shop/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/about'
    | '/nav'
    | '/posts'
    | '/_pathlessLayout/dashboard'
    | '/nav/redirect'
    | '/nav/search'
    | '/posts/$'
    | '/posts/$postId'
    | '/products/{-$category}'
    | '/shop/products'
    | '/nav/'
    | '/posts/'
    | '/posts_/$postId/edit'
    | '/shop/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  NavRoute: typeof NavRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProductsChar123CategoryChar125Route: typeof ProductsChar123CategoryChar125Route
  ShopProductsRoute: typeof ShopProductsRouteWithChildren
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav': {
      id: '/nav'
      path: '/nav'
      fullPath: '/nav'
      preLoaderRoute: typeof NavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/nav/': {
      id: '/nav/'
      path: '/'
      fullPath: '/nav/'
      preLoaderRoute: typeof NavIndexRouteImport
      parentRoute: typeof NavRoute
    }
    '/shop/products': {
      id: '/shop/products'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/{-$category}': {
      id: '/products/{-$category}'
      path: '/products/{-$category}'
      fullPath: '/products/{-$category}'
      preLoaderRoute: typeof ProductsChar123CategoryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatRouteImport
      parentRoute: typeof PostsRoute
    }
    '/nav/search': {
      id: '/nav/search'
      path: '/search'
      fullPath: '/nav/search'
      preLoaderRoute: typeof NavSearchRouteImport
      parentRoute: typeof NavRoute
    }
    '/nav/redirect': {
      id: '/nav/redirect'
      path: '/redirect'
      fullPath: '/nav/redirect'
      preLoaderRoute: typeof NavRedirectRouteImport
      parentRoute: typeof NavRoute
    }
    '/_pathlessLayout/dashboard': {
      id: '/_pathlessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessLayoutDashboardRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/shop/products/$productId': {
      id: '/shop/products/$productId'
      path: '/$productId'
      fullPath: '/shop/products/$productId'
      preLoaderRoute: typeof ShopProductsProductIdRouteImport
      parentRoute: typeof ShopProductsRoute
    }
    '/posts_/$postId/edit': {
      id: '/posts_/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutDashboardRoute: typeof PathlessLayoutDashboardRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutDashboardRoute: PathlessLayoutDashboardRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface NavRouteChildren {
  NavRedirectRoute: typeof NavRedirectRoute
  NavSearchRoute: typeof NavSearchRoute
  NavIndexRoute: typeof NavIndexRoute
}

const NavRouteChildren: NavRouteChildren = {
  NavRedirectRoute: NavRedirectRoute,
  NavSearchRoute: NavSearchRoute,
  NavIndexRoute: NavIndexRoute,
}

const NavRouteWithChildren = NavRoute._addFileChildren(NavRouteChildren)

interface PostsRouteChildren {
  PostsSplatRoute: typeof PostsSplatRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSplatRoute: PostsSplatRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ShopProductsRouteChildren {
  ShopProductsProductIdRoute: typeof ShopProductsProductIdRoute
}

const ShopProductsRouteChildren: ShopProductsRouteChildren = {
  ShopProductsProductIdRoute: ShopProductsProductIdRoute,
}

const ShopProductsRouteWithChildren = ShopProductsRoute._addFileChildren(
  ShopProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  NavRoute: NavRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProductsChar123CategoryChar125Route: ProductsChar123CategoryChar125Route,
  ShopProductsRoute: ShopProductsRouteWithChildren,
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
